name: Auto-Release packages on Version Change

on:
  workflow_call:
    inputs:
      default-branch:
        description: 'The default branch to check for pushes'
        required: true
        type: string
    secrets:
      token:
        description: 'The GITHUB_TOKEN from the calling repo'
        required: true

jobs:
  check-version-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get version changes
        id: get_versions
        run: |
          # Get current version from the latest commit (HEAD)
          CURRENT_VERSION=$(jq -r .version composer.json)
          
          # Get the version from the previous commit (HEAD~1)
          PREVIOUS_VERSION=$(git show HEAD~1:composer.json | jq -r .version || echo "0.0.0")
          
          echo "Current version: $CURRENT_VERSION"
          echo "Previous version: $PREVIOUS_VERSION"
          
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          
          if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Tag and Release on Version Change
        if: steps.get_versions.outputs.version_changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
          TAG: ${{ steps.get_versions.outputs.current_version }}
        run: |
          echo "Version changed to $TAG. Creating release."

          if git rev-parse "refs/tags/$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists. No new release will be created."
            exit 0
          fi

          gh release create "$TAG" \
            --title "Release $TAG" \
            --notes "Automatic release triggered by version change to $TAG in composer.json."

      - name: No Version Change
        if: steps.get_versions.outputs.version_changed == 'false'
        run: echo "No version change detected. No new release will be created."