name: Update Kustomize Image (Gitflow overlays)

on:
  workflow_call:
    inputs:
      kustomize_image:
        required: true
        type: string
      image_tag:
        required: true
        type: string

jobs:
  update-kustomize:
    runs-on: ubuntu-latest
    environment: |
      ${{
           github.ref_name == 'master'  && 'Production'
        || github.ref_name == 'main'    && 'Production'
        || github.ref_name == 'develop' && 'Testing'
        || startsWith(github.ref_name, 'release/') && 'Acceptance'
        || 'Unknown'
      }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Determine overlay path
        id: overlay
        run: |
          if [[ "$GITHUB_REF" == "develop" ]]; then
            OVERLAY=".k8s/overlays/testing"
          elif [[ "$GITHUB_REF" == release/* ]]; then
            OVERLAY=".k8s/overlays/acceptance"
          elif [[ "$GITHUB_REF" == main || "$GITHUB_REF" == master ]]; then
            OVERLAY=".k8s/overlays/production"
          else
            echo "Branch not mapped to overlay, exiting"
            exit 0
          fi
          echo "overlay_path=$OVERLAY" >> $GITHUB_OUTPUT

      - name: Install kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          mv kustomize /usr/local/bin/

      - name: Set image in kustomization.yaml
        run: |
          cd ${{ steps.overlay.outputs.overlay_path }}
          kustomize edit set image ${{ inputs.kustomize_image }}=${{ inputs.image_tag }}

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update image to ${{ inputs.image_tag }} [skip ci]" || echo "No changes"
          git push

